/* VIR — banque de questions
   Une question = { id, module, question, options: [4 réponses], answer: index de la bonne réponse, explanation }.
   Pour le futur espace formateur : ce tableau pourra être remplacé par un appel API
   sans toucher à quiz.js (il lit uniquement window.VIR_QUIZ). */
window.VIR_QUIZ = {
  modules: {
    1: "Rôle de la VIR",
    2: "Conditions de déploiement",
    3: "Doctrine d’intervention"
  },
  questions: [
    /* ---------- Module 1 : Rôle de la VIR ---------- */
    { id: "m1-01", module: 1, question: "Que signifie VIR ?",
      options: ["Véhicule d’Intervention Rapide", "Véhicule d’Inspection Routière", "Voiture d’Intervention Renforcée", "Véhicule d’Interception Radar"], answer: 0,
      explanation: "VIR signifie Véhicule d’Intervention Rapide." },
    { id: "m1-02", module: 1, question: "Quelle est la mission principale de la VIR ?",
      options: ["Les patrouilles de routine", "Les courses-poursuites à haute vitesse", "Le transport des suspects", "Les contrôles routiers classiques"], answer: 1,
      explanation: "La VIR intervient en priorité sur les courses-poursuites à haute vitesse." },
    { id: "m1-03", module: 1, question: "Lequel de ces cas relève de la mission de la VIR ?",
      options: ["Un contrôle de papiers de routine", "Une prise de plainte au poste", "Un Go Fast", "Une surveillance de quartier"], answer: 2,
      explanation: "Go Fast, refus d’obtempérer et ventes de drogue font partie des interventions prioritaires de la VIR." },
    { id: "m1-04", module: 1, question: "Quel est l’objectif de la VIR ?",
      options: ["Remplacer les patrouilles classiques", "Assurer une intervention efficace, rapide et adaptée quand les patrouilles classiques sont dépassées", "Surveiller toute la ville en continu", "Escorter les autres unités"], answer: 1,
      explanation: "La VIR est là quand les patrouilles classiques sont dépassées, pas pour les remplacer." },
    { id: "m1-05", module: 1, question: "Comment la VIR intervient-elle par rapport aux autres patrouilles ?",
      options: ["Seule, sans aucune autre unité", "En complément des autres patrouilles", "En remplacement des patrouilles", "Uniquement après la fin de la poursuite"], answer: 1,
      explanation: "La VIR intervient en complément des autres patrouilles." },
    { id: "m1-06", module: 1, question: "Quelle position la VIR prend-elle automatiquement sur une poursuite ?",
      options: ["P3", "P2", "P1", "Aucune, elle attend les ordres"], answer: 2,
      explanation: "Elle prend automatiquement la P1 (Pilote 1)." },
    { id: "m1-07", module: 1, question: "Dans quel cas la VIR ne prend-elle pas la P1 ?",
      options: ["Si une patrouille Adam est présente", "Si une unité MSG est déjà sur les lieux", "Si la poursuite dure plus de 10 minutes", "Si la VIR n’a pas de copilote"], answer: 1,
      explanation: "Sauf si une unité MSG est déjà présente sur les lieux." },
    { id: "m1-08", module: 1, question: "Que signifie P1 ?",
      options: ["Patrouille 1", "Pilote 1", "Poursuite 1", "Position 1 en ville"], answer: 1,
      explanation: "P1 signifie Pilote 1 : le premier véhicule de la poursuite." },

    /* ---------- Module 2 : Conditions de déploiement ---------- */
    { id: "m2-01", module: 2, question: "Lequel de ces motifs autorise l’engagement de la VIR ?",
      options: ["Un contrôle lambda", "Un véhicule haute performance en fuite ou un Go Fast", "Une simple demande de renseignement", "Un stationnement gênant"], answer: 1,
      explanation: "Poursuite contre un véhicule haute performance, Go Fast ou délit de fuite." },
    { id: "m2-02", module: 2, question: "Un refus d’obtempérer justifie la VIR quand…",
      options: ["Il a lieu la nuit", "Il présente un danger imminent ou une grosse scène", "Le conducteur est connu des services", "Aucune patrouille n’est en ville"], answer: 1,
      explanation: "Danger imminent ou grosse scène (braquage PDM, banque, etc.)." },
    { id: "m2-03", module: 2, question: "Que dit la doctrine sur l’usage de la VIR en patrouille basique ?",
      options: ["C’est son usage normal", "C’est autorisé le week-end", "C’est déconseillé : elle reste un véhicule d’intervention ciblée", "C’est obligatoire si une seule patrouille est en ville"], answer: 2,
      explanation: "Routine et contrôles lambda sont déconseillés." },
    { id: "m2-04", module: 2, question: "Un agent peut-il sortir la VIR sans formation VIR validée ?",
      options: ["Oui, avec l’accord d’un collègue", "Oui, en cas de renfort radio", "Oui, s’il est expérimenté", "Non, c’est strictement interdit"], answer: 3,
      explanation: "La sortie sans qualification ou formation VIR validée est strictement interdite." },
    { id: "m2-05", module: 2, question: "Combien de patrouilles minimum faut-il en ville pour sortir la VIR ?",
      options: ["1", "2", "3", "4"], answer: 1,
      explanation: "La sortie est autorisée uniquement s’il y a au moins 2 patrouilles en ville." },
    { id: "m2-06", module: 2, question: "Il y a 3 unités Adam en ville et une VIR est déjà sortie. Peut-on en sortir une seconde ?",
      options: ["Oui, si l’agent est qualifié", "Oui, avec l’accord du dispatch", "Non, c’est interdit", "Oui, uniquement de nuit"], answer: 2,
      explanation: "Avec 3 unités Adam et 1 VIR, il est interdit d’en sortir une seconde." },
    { id: "m2-07", module: 2, question: "Quelle annonce radio est obligatoire lorsqu’on part en VIR ?",
      options: ["« VIR [Matricule] 10-41 tout secteur »", "« VIR en route pour le poste »", "« VIR [Matricule] 10-19 pour 10-14 »", "« Adam [Matricule] actuellement en VIR »"], answer: 0,
      explanation: "L’annonce est « VIR [Matricule] 10-41 tout secteur »." },
    { id: "m2-08", module: 2, question: "Comment doit-on s’annoncer en radio à chaque call ?",
      options: ["Avec son prénom", "Avec l’indicatif Adam", "Seulement au début du service", "Avec l’indicatif VIR à chaque prise de parole"], answer: 3,
      explanation: "L’agent s’annonce avec l’indicatif VIR à chaque prise de parole." },
    { id: "m2-09", module: 2, question: "Combien de places compte la VIR ?",
      options: ["1", "2", "3", "4"], answer: 1,
      explanation: "2 places : un pilote et un copilote (radio et GPS)." },
    { id: "m2-10", module: 2, question: "Que faire après l’interpellation d’un suspect ?",
      options: ["Le transporter dans la VIR", "Le faire monter à la place du copilote", "Demander impérativement une autre unité sur zone", "Le laisser sur place"], answer: 2,
      explanation: "Le transport de suspect est interdit en règle générale : il faut demander une autre unité." },
    { id: "m2-11", module: 2, question: "Quand le transport d’un suspect en VIR est-il toléré ?",
      options: ["Jamais, sans exception", "En extrême urgence ou en l’absence totale d’autres patrouilles", "Quand le suspect est coopératif", "Quand la destination est proche"], answer: 1,
      explanation: "Exception : extrême urgence ou absence totale d’autres patrouilles." },

    /* ---------- Module 3 : Doctrine d’intervention ---------- */
    { id: "m3-01", module: 3, question: "Quel est le rôle du véhicule en P1 ?",
      options: ["Bloquer la route", "Maintenir le visuel et conduire la poursuite", "Relayer la radio uniquement", "Anticiper et appuyer les unités"], answer: 1,
      explanation: "P1 : premier véhicule, maintien du visuel et conduite de la poursuite." },
    { id: "m3-02", module: 3, question: "Quel est le rôle du véhicule en P2 ?",
      options: ["Soutien direct et relais radio", "Conduite de la poursuite", "Transport du suspect", "Contrôle du périmètre"], answer: 0,
      explanation: "P2 : soutien direct, relais radio et soutien immédiat." },
    { id: "m3-03", module: 3, question: "Quel est le rôle du véhicule en P3 ?",
      options: ["Prendre la tête", "Relayer la radio", "Anticiper et appuyer les unités engagées", "Se retirer de la poursuite"], answer: 2,
      explanation: "P3 : soutien, anticipation et appui aux unités engagées (si une demande de 10-33 a été faite)." },
    { id: "m3-04", module: 3, question: "En P1, que doit faire la VIR vis-à-vis du suspect ?",
      options: ["Le percuter pour l’arrêter", "Maintenir le visuel sans le percuter", "Le doubler pour le bloquer", "Rester à distance sans visuel"], answer: 1,
      explanation: "La VIR prend la tête pour maintenir le visuel sans le percuter." },
    { id: "m3-05", module: 3, question: "La MSG arrive sur la poursuite. Que fait la VIR ?",
      options: ["Elle garde la P1", "Elle quitte la poursuite", "Elle cède la P1 et repasse en P2", "Elle passe en P3"], answer: 2,
      explanation: "Elle cède immédiatement la P1 à la MSG et repasse en P2." },
    { id: "m3-06", module: 3, question: "Une patrouille classique est en P1. Que fait la VIR ?",
      options: ["Elle la dépasse directement", "Elle demande clairement le dépassement en radio", "Elle klaxonne pour l’avertir", "Elle reste en P3 sans rien dire"], answer: 1,
      explanation: "La VIR demande le dépassement de manière claire en radio." },
    { id: "m3-07", module: 3, question: "Quelle est la bonne formulation radio pour demander le dépassement ?",
      options: ["« VIR pour Adam 69, demande de dépassement pour prise de P1 »", "« VIR à toutes les unités, je double la P1 »", "« VIR pour Adam 69, décalez-vous, je passe »", "« VIR [Matricule] 10-41 tout secteur »"], answer: 0,
      explanation: "« VIR pour Adam 69, demande de dépassement pour prise de P1 »." },
    { id: "m3-08", module: 3, question: "Après avoir demandé le dépassement, que fait la VIR ?",
      options: ["Elle double aussitôt", "Elle attend l’autorisation ou le décalage de l’unité", "Elle repasse en P3", "Elle coupe la radio"], answer: 1,
      explanation: "La VIR attend l’autorisation ou le décalage avant d’engager le dépassement." },
    { id: "m3-09", module: 3, question: "Quelle annonce radio fait la VIR pour prendre la P1 ?",
      options: ["« VIR [Matricule] je prends la P1 sur le 10-31 »", "« Adam [Matricule] je prends la P1 »", "« VIR à toutes les unités, je passe devant »", "« VIR [Matricule] 10-41 tout secteur »"], answer: 0,
      explanation: "La VIR annonce sa prise de P1 avec son indicatif et son matricule : « VIR [Matricule] je prends la P1 sur le 10-31 »." }
  ]
};